[package]
name = "cosmic-randr-shell"
version = "0.1.0"
description = "Wrapper for the cosmic-randr CLI"
license = "MPL-2.0"
edition = "2024"

[dependencies]
kdl = "6.5.0"
slotmap = { version = "1.0.7" }
thiserror = "2.0.17"
